### ISSUE TITLE
Photos taken in Seek on a Nexus 5 are saved upside-down

### ISSUE THREAD

**Issue by tiwane** [inaturalist/react-native-inat-camera#10]
Like these sad bananas:

![IMG_20190411_123057](https://user-images.githubusercontent.com/15896181/55991283-bd0df300-5c5e-11e9-8aef-f0dc7961d736.jpg)

Here's the photo with metadata: https://www.dropbox.com/s/827iztks0txlk60/IMG_20190411_123057.jpg?dl=0

**Comment by albullington** [comment]
Closing this since I haven't heard any complaints about upside-down photos in the past year. Feel free to reopen if this is still happening.
