### ISSUE TITLE
attempt to incorporate frequency data into react-native-inat-camera CV predictions

### ISSUE THREAD

**Issue by loarie** [inaturalist/react-native-inat-camera#42]
The iNat CV API uses both the vector of scores from the CV model and also a vector of gridded frequencies (e.g. 100 obs of species X and 10 obs of species Y) stored in Redis to produce the final suggestions. In other words, the suggestions combine 2 vectors - one from the CV model and a frequency vector corresponding to the grid cell and month overlapping the observation.

We'd like to explore whether its possible to do something similar in the react native inat camera.  @budowski what other information do you need to start exploring this?

**Comment by jtklein** [comment]
Closing this off because I think that if implemented this would be in a separate native package. Basically, sending a location to a native package and retrieving the frequency vector. Combining them would happen in the client.
