### ISSUE TITLE
Alternating camera errors, Android 8

### ISSUE THREAD

**Issue by albullington** [inaturalist/react-native-inat-camera#67]
Someone using a Moto Z2 Play, Android 8.0.0 ran into both of these errors + an app crash within a 5 minute session. They said the errors happened:

1. while they were trying to run the classifier on various plants and
2. while switching between the photo library and the camera

Not sure if there's anything we can do here, but I am curious why they might be getting more than one type of error.

![Screenshot_20210622-125105](https://user-images.githubusercontent.com/35536439/123010191-f714cc80-d372-11eb-9b69-9c6123aa3d6d.png)
![Screenshot_20210622-124832](https://user-images.githubusercontent.com/35536439/123010195-f8de9000-d372-11eb-9640-9a663dba6679.png)

**Comment by budowski** [comment]
@albullington - can he send us log files right this is happening? Since they can show us the internal flow of the library before this error occurred

**Comment by tiwane** [comment]
Do you mean "right after" this is happens?

**Comment by budowski** [comment]
Oops, yes - I mean "right after" :-)
