### ISSUE TITLE
In Android - camera has black bar on right-hand side, low res, and throws up an error

### ISSUE THREAD

**Issue by tiwane** [inaturalist/react-native-inat-camera#74]
A user with a Sony Xperia 5 II says the camera is not functioning well. "Very low resolution camera preview, a black bar on the right hand side of the camera preview and occasional black screen with error." They weren't able to get a log file, but here are two screenshots:

![Screenshot_20210917-005339](https://user-images.githubusercontent.com/15896181/133897660-ba22a606-3686-4a26-be4f-b1f459786fdf.png)

![Screenshot_20210916-171732(1)](https://user-images.githubusercontent.com/15896181/133897658-9d051268-707f-4632-a9c2-17785a56ffdd.png)

Trying to get Seek and OS version info.

**Comment by tiwane** [comment]
Some further details. 

The error message usually appears after they
> Open seek with live camera view > switch to the photo option on the bottom right > switch back to camera view > black screen with error message when taking photo.

Weird crop:
>The cropping error is intermittent and I can’t figure out a specific way to reproduce the error but it has something to do with switching backwards and forwards between the live view camera and the menus e.g: challenges

And more info about the device's camera:
>When any app uses the back cameras on my device it does some sort of start up routine, I know this because you can audibly hear the OIS click for each camera each startup. What happens is I hear the click on first open of live view but after switching to something else and back to live view it does not go through the “click” routine. It is a strange Sony quality.

**Comment by albullington** [comment]
The black bar might have to do with [this line](https://github.com/inaturalist/SeekReactNative/blob/8e5fcb8278140ea5140eb2d85992faf868050c39/components/Camera/ARCamera/ARCamera.js#L355) in the RN code. On Android devices, we've always added 100px to the camera width to *avoid* showing a black line on the right side of the screen. This seems to fill the screen on most devices, but maybe it doesn't work correctly for the Sony Xperia 5 II.

Ideally, I think we'd want to get the camera height/width correct in the native code so there's no need for extra (or Platform-specific) styling in RN.
