### ISSUE TITLE
Camera won't load model after being device is put to sleep

### ISSUE THREAD

**Issue by tiwane** [inaturalist/react-native-inat-camera#79]
Seek 2.13.0 (229). Pixel 3a, Android 11.

1. Open Seek camera, make sure it's providing ID suggestions.
2. With Seek camera still open, put device to sleep.
3. Wake device.
4. The camera will work, but no new IDs are suggested. If an ID was on the screen when device was put to sleep, it stays there.

![image](https://user-images.githubusercontent.com/15896181/138813677-52c5898d-f249-4bd1-a585-9f58a5d81d08.png)

Log at https://inaturalist.slack.com/archives/C9KMT4MK2/p1635200395006400

**Comment by jtklein** [comment]
I can not replicate this in the vision-camera branch anymore.
